
// This configuration is automatically generated by Firebase Studio.
// Do not edit this file manually.

// This configuration is designed to work with Firebase App Hosting's automatic
// configuration, while also providing a fallback for local development.
// It is safe to expose this configuration to the client-side.

export const firebaseConfig = {
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || "studio-8000668733-7e3c3",
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || "1:507954317689:web:1dd490812faa9d345787a8",
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || "AIzaSyAmN9-TyZBXv9B7j6KfFWBzHfdpFMFy4bk",
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || "studio-8000668733-7e3c3.firebaseapp.com",
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || "507954317689",
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || "",
};

export const isFirebaseConfigured = () => {
    return firebaseConfig.projectId && firebaseConfig.apiKey;
}
